user_dir: "/home"
app_port: 5000
service:
  workingdir: "{{user_dir}}/django-project/myproject"
  execstart: "{{user_dir}}/django-project/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 myproject.wsgi:application"

djangoservice:
  workingdir: "{{user_dir}}/django-project/myproject"
  execstart: "{{user_dir}}/django-project/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 myproject.wsgi:application"



app:
  env:
    SQLALCHEMY_DATABASE_URI: postgresql://admin:pass123@db01/db
    SQLALCHEMY_TRACK_MODIFICATIONS: False
    SECRET_KEY: proto007

django:
  env:
    SECRET_KEY: 'proto007'
    DATABASE_URL: 'postgresql://admin:pass123@db01/db'