---
loadbalancer:
  hosts:
    lb01:
      ansible_host: lb01
webserver:
  hosts:
    app01:
      ansible_host: app01
    app02:
      ansible_host: app02
database:
  hosts:
    db01:
      ansible_host: db01  
control:
  hosts:
    control:
      ansible_connection: local
