---
loadbalancer:
  hosts:
    lb:
      ansible_host: lb
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
  vars:
    ansible_python_interpreter: /usr/bin/python3
webserver:
  hosts:
    app:
      ansible_host: app
  vars:
    ansible_python_interpreter: /usr/bin/python3
database:
  hosts:
    db:
      ansible_host: db
  vars:
    ansible_python_interpreter: /usr/bin/python3
control:
  hosts:
    control:
      ansible_connection: local