---
loadbalancer:
  hosts:
    lb01:
      ansible_host: lb01
webserver:
  hosts:
    app01:
      ansible_host: app01
    app02:
      ansible_host: app02
database:
  hosts:
    db01:
      ansible_host: db01  
control:
  hosts:
    control:
      ansible_connection: local
azurehosts:
  hosts:
    devopsvm:
      ansible_host: devopsvm
      ansible_port: 22
      ansible_ssh_user: azureuser
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    deployment:
      ansible_host: deployment
      ansible_port: 22