---
loadbalancer:
  hosts:
    lb01:
      ansible_connection: local
webserver:
  hosts:
    devopsvm:
      ansible_host: 20.56.93.232
      ansible_port: 22
      ansible_ssh_user: azureuser
  vars:
    ansible_python_interpreter: /usr/bin/python3
database:
  hosts:
    deployment1:
      ansible_host: 20.86.34.7
      ansible_port: 22
      ansible_ssh_user: azureuser
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
  vars:
    ansible_python_interpreter: /usr/bin/python3
control:
  hosts:
    control:
      ansible_connection: local