---
deploymentservers:
  hosts:
    deployment1:
      ansible_host: 20.86.34.7
      ansible_port: 22
      ansible_ssh_user: azureuser
  vars:
    ansible_python_interpreter: /usr/bin/python3

database:
  hosts:
    devopsvm:
      ansile_host: 20.56.93.232
      ansible_port: 22
      ansible_ssh_user: azureuser
  vars:
    ansible_python_interpreter: /usr/bin/python3